language: node_js
node_js:
  - 'node'
services:
  - docker
jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm test
    - stage: docker-deploy-image
      script:
        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        - docker build -t indiragogineni/ci-test .
        - docker push indiragogineni/ci-test
    - stage: deploy
      script: skip
      deploy:
        provider: elasticbeanstalk
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        region: 'us-east-2'
        app: 'CI Test'
        env: 'Citest-env'
        bucket_name: 'elasticbeanstalk-us-east-2-499607391646'
        bucket_path: 'CI Test'
